'use client';

import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';

const SUPABASE_URL='https://vxptgfnuxboprwhgcxpd.supabase.co';
const SUPABASE_KEY='sb_publishable_Wu0xH_TZ9L5t72BnROPtnw_9eJbG88T';
async function sb(path,token){return fetch(`${SUPABASE_URL}${path}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`},cache:'no-store'});}
const money=n=>`$${Number(n||0).toFixed(2)}`;
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};

export default function DailyOverview(){
 const[host,setHost]=useState(null);const[requests,setRequests]=useState([]);const[quotes,setQuotes]=useState([]);const[jobs,setJobs]=useState([]);const[ready,setReady]=useState(false);
 async function load(){const token=localStorage.getItem('uw_owner_token');if(!token)return;const[rr,qr,jr]=await Promise.all([sb('/rest/v1/public_service_requests_v1?select=*&order=created_at.desc&limit=100',token),sb('/rest/v1/public_request_quotes_v1?select=*&order=created_at.desc&limit=100',token),sb('/rest/v1/public_jobs_v1?select=*&order=scheduled_date.asc.nullslast,created_at.asc&limit=100',token)]);if(rr.ok&&qr.ok&&jr.ok){setRequests(await rr.json());setQuotes(await qr.json());setJobs(await jr.json());setReady(true);}}
 useEffect(()=>{let root;function mount(){const top=document.querySelector('.ownerTop');if(!top||!localStorage.getItem('uw_owner_token'))return false;root=document.getElementById('uw-daily-overview-host');if(!root){root=document.createElement('div');root.id='uw-daily-overview-host';top.insertAdjacentElement('afterend',root);}setHost(root);return true;}if(!mount()){const o=new MutationObserver(()=>{if(mount())o.disconnect()});o.observe(document.body,{childList:true,subtree:true});setTimeout(()=>o.disconnect(),10000);}load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[]);
 const data=useMemo(()=>{const today=localDate();const openRequests=requests.filter(r=>!quotes.some(q=>q.request_id===r.id&&['approved','declined'].includes(q.status)));const awaiting=quotes.filter(q=>q.status==='sent');const approvedUnscheduled=quotes.filter(q=>q.status==='approved'&&!jobs.some(j=>j.quote_id===q.id));const todayJobs=jobs.filter(j=>j.scheduled_date===today&&!['complete','cancelled'].includes(j.status));const unpaid=jobs.filter(j=>j.status==='complete'&&!j.paid_at);const waitingParts=jobs.filter(j=>j.status==='waiting_parts');const outstanding=unpaid.reduce((sum,j)=>{const q=quotes.find(q=>q.id===j.quote_id);return sum+Number(q?.total||0)},0);return{openRequests,awaiting,approvedUnscheduled,todayJobs,unpaid,waitingParts,outstanding};},[requests,quotes,jobs]);
 if(!host||!ready)return null;const attention=[data.openRequests.length&&`${data.openRequests.length} service request${data.openRequests.length===1?'':'s'} need review`,data.awaiting.length&&`${data.awaiting.length} estimate${data.awaiting.length===1?'':'s'} awaiting customer approval`,data.approvedUnscheduled.length&&`${data.approvedUnscheduled.length} approved quote${data.approvedUnscheduled.length===1?'':'s'} need scheduling`,data.waitingParts.length&&`${data.waitingParts.length} job${data.waitingParts.length===1?'':'s'} waiting on parts`,data.unpaid.length&&`${data.unpaid.length} completed invoice${data.unpaid.length===1?'':'s'} unpaid`].filter(Boolean);
 return createPortal(<section className="dailyOverview"><div className="dailyOverviewHead"><div><p className="kicker">DAILY OPERATIONS</p><h2>Today's Overview</h2></div><span>{new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</span></div><div className="dailyMetrics"><button onClick={()=>document.querySelector('.ownerTabs button')?.click()}><strong>{data.openRequests.length}</strong><span>Pending Requests</span></button><div><strong>{data.todayJobs.length}</strong><span>Today's Jobs</span></div><div><strong>{data.awaiting.length}</strong><span>Awaiting Approval</span></div><div><strong>{data.unpaid.length}</strong><span>Unpaid Invoices</span></div><div><strong>{money(data.outstanding)}</strong><span>Outstanding Balance</span></div></div><div className="needsAttention"><h3>Needs Attention</h3>{attention.length?<div className="attentionList">{attention.map((item,i)=><p key={i}><b>!</b>{item}</p>)}</div>:<p className="allClear">No immediate items need attention.</p>}</div>{data.todayJobs.length>0&&<div className="todayJobs"><h3>Today's Jobs</h3>{data.todayJobs.map(j=>{const r=requests.find(r=>r.id===j.request_id);return <div key={j.id}><span><b>{j.arrival_window||'Flexible'}</b>{r?.customer_name||'Customer'} · {r?.year_make_model||'Vehicle'}</span><small>{j.status==='waiting_parts'?'Waiting on Parts':j.status==='in_progress'?'In Progress':'Scheduled'}</small></div>})}</div>}</section>,host);
}
