'use client';

import { useEffect, useState } from 'react';

const SUPABASE_URL='https://vxptgfnuxboprwhgcxpd.supabase.co';
const SUPABASE_KEY='sb_publishable_Wu0xH_TZ9L5t72BnROPtnw_9eJbG88T';
const tabs=[['requests','Requests'],['approved','Approved Quotes'],['next','Next Jobs'],['unpaid','Complete / Unpaid'],['paid','Paid Invoices']];
async function sb(path,options={},token){return fetch(`${SUPABASE_URL}${path}`,{...options,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token||SUPABASE_KEY}`,'Content-Type':'application/json',...(options.headers||{})},cache:'no-store'});}
const money=n=>`$${Number(n||0).toFixed(2)}`;

export default function OwnerDashboard(){
 const[token,setToken]=useState(''); const[email,setEmail]=useState(''); const[password,setPassword]=useState(''); const[requests,setRequests]=useState([]); const[quotes,setQuotes]=useState([]); const[message,setMessage]=useState(''); const[loading,setLoading]=useState(false); const[tab,setTab]=useState('requests'); const[editing,setEditing]=useState(''); const[quote,setQuote]=useState({labor:'',parts:'',service_call:'75',supplies:'',tax:'',notes:''});
 async function load(t){setLoading(true);const [rr,qr]=await Promise.all([sb('/rest/v1/public_service_requests_v1?select=*&order=created_at.desc&limit=100',{},t),sb('/rest/v1/public_request_quotes_v1?select=*&order=created_at.desc&limit=100',{},t)]);if(rr.ok&&qr.ok){setRequests(await rr.json());setQuotes(await qr.json());setMessage('');}else if(rr.status===401||qr.status===401){setToken('');localStorage.removeItem('uw_owner_token');setMessage('Your session expired. Please sign in again.');}else setMessage('Unable to load owner data. This account may not have staff access.');setLoading(false);}
 useEffect(()=>{const saved=localStorage.getItem('uw_owner_token');if(saved){setToken(saved);load(saved);}},[]);
 async function login(e){e.preventDefault();setLoading(true);setMessage('');const res=await sb('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});const data=await res.json();if(!res.ok||!data.access_token){setMessage('Sign-in failed. Check your email and password.');setLoading(false);return;}localStorage.setItem('uw_owner_token',data.access_token);setToken(data.access_token);setPassword('');await load(data.access_token);}
 async function setStatus(id,status){const res=await sb(`/rest/v1/public_service_requests_v1?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status})},token);if(res.ok)load(token);else setMessage('Could not update that request.');}
 function openQuote(r){const existing=quotes.find(q=>q.request_id===r.id);setEditing(r.id);setQuote(existing?{labor:existing.labor,parts:existing.parts,service_call:existing.service_call,supplies:existing.supplies,tax:existing.tax,notes:existing.notes||''}:{labor:'',parts:'',service_call:'75',supplies:'',tax:'',notes:''});}
 async function saveQuote(requestId,status='draft'){const existing=quotes.find(q=>q.request_id===requestId);const payload={request_id:requestId,labor:Number(quote.labor||0),parts:Number(quote.parts||0),service_call:Number(quote.service_call||0),supplies:Number(quote.supplies||0),tax:Number(quote.tax||0),notes:quote.notes||null,status,updated_at:new Date().toISOString(),...(status==='approved'?{approved_at:new Date().toISOString()}:{})};let res;if(existing)res=await sb(`/rest/v1/public_request_quotes_v1?id=eq.${existing.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)},token);else res=await sb('/rest/v1/public_request_quotes_v1',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)},token);if(!res.ok){setMessage('Could not save quote.');return;}if(status==='approved')await setStatus(requestId,'scheduled');setEditing('');await load(token);if(status==='approved')setTab('approved');}
 function logout(){localStorage.removeItem('uw_owner_token');setToken('');setRequests([]);setQuotes([]);setEmail('');}
 if(!token)return <main className="ownerPage"><section className="ownerLogin"><p className="kicker">ULTIMATE WRENCHWORKS · V1.7</p><h1>Owner Dashboard</h1><p>Private business management access.</p><form onSubmit={login}><label><span>Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label><span>Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary" disabled={loading}>{loading?'Signing in…':'Sign In'}</button></form>{message&&<p className="ownerMessage">{message}</p>}<a href="/">← Back to website</a></section></main>;
 const approved=quotes.filter(q=>q.status==='approved'); const title=tabs.find(x=>x[0]===tab)?.[1];
 function card(r,showQuote=true){const q=quotes.find(x=>x.request_id===r.id);return <article className="requestItem" key={r.id}><div className="requestHead"><div><span className="statusPill">{q?.status||r.status}</span><h2>{r.customer_name}</h2><p>{r.service_type} · {r.year_make_model}</p></div><time>{new Date(r.created_at).toLocaleString()}</time></div><div className="requestDetails"><div><b>Phone</b><a href={`tel:${r.phone}`}>{r.phone}</a></div><div><b>Email</b>{r.email?<a href={`mailto:${r.email}`}>{r.email}</a>:<span>Not provided</span>}</div><div><b>Preferred date</b><span>{r.preferred_date||'Flexible'}</span></div><div><b>Timeframe</b><span>{r.preferred_timeframe||'Flexible'}</span></div><div><b>Location</b><span>{r.service_location}</span></div></div><div className="requestProblem"><b>Customer notes</b><p>{r.problem_description}</p></div>{q&&<div className="quoteSummary"><b>Quote total</b><strong>{money(q.total)}</strong>{q.notes&&<p>{q.notes}</p>}</div>}{showQuote&&<><div className="statusButtons"><button className="active" onClick={()=>openQuote(r)}>{q?'Edit Quote':'Create Quote'}</button>{['contacted','closed'].map(s=><button key={s} onClick={()=>setStatus(r.id,s)}>{s}</button>)}</div>{editing===r.id&&<div className="quoteEditor"><h3>{q?'Edit Quote':'Create Quote'}</h3><div className="formGrid"><label><span>Labor</span><input type="number" min="0" step="0.01" value={quote.labor} onChange={e=>setQuote({...quote,labor:e.target.value})}/></label><label><span>Parts</span><input type="number" min="0" step="0.01" value={quote.parts} onChange={e=>setQuote({...quote,parts:e.target.value})}/></label><label><span>Service call</span><input type="number" min="0" step="0.01" value={quote.service_call} onChange={e=>setQuote({...quote,service_call:e.target.value})}/></label><label><span>Supplies</span><input type="number" min="0" step="0.01" value={quote.supplies} onChange={e=>setQuote({...quote,supplies:e.target.value})}/></label><label><span>Tax</span><input type="number" min="0" step="0.01" value={quote.tax} onChange={e=>setQuote({...quote,tax:e.target.value})}/></label><label className="wide"><span>Quote notes</span><textarea rows="3" value={quote.notes} onChange={e=>setQuote({...quote,notes:e.target.value})}/></label></div><div className="statusButtons"><button onClick={()=>saveQuote(r.id,'draft')}>Save Draft</button><button onClick={()=>saveQuote(r.id,'sent')}>Mark Sent</button><button className="active" onClick={()=>saveQuote(r.id,'approved')}>Mark Approved</button><button onClick={()=>setEditing('')}>Cancel</button></div></div>}</>}</article>}
 return <main className="ownerPage"><div className="ownerTop"><div><p className="kicker">ULTIMATE WRENCHWORKS · V1.7</p><h1>Owner Dashboard</h1></div><div className="ownerActions"><button onClick={()=>load(token)}>{loading?'Refreshing…':'Refresh'}</button><button onClick={logout}>Sign Out</button></div></div><nav className="ownerTabs">{tabs.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}{key==='requests'&&requests.length>0?<span>{requests.filter(r=>!quotes.some(q=>q.request_id===r.id&&q.status==='approved')).length}</span>:null}{key==='approved'&&approved.length>0?<span>{approved.length}</span>:null}</button>)}</nav>{message&&<p className="ownerMessage">{message}</p>}<div className="tabHeading"><h2>{title}</h2><p>{tab==='requests'?'Review incoming requests and prepare customer quotes.':tab==='approved'?'Quotes approved and ready to move into the work queue.':'This workflow section is ready for the next job-management build.'}</p></div>{tab==='requests'?<section className="requestList">{requests.filter(r=>!quotes.some(q=>q.request_id===r.id&&q.status==='approved')).map(r=>card(r))}{requests.length===0&&!loading&&<div className="emptyInbox">No website requests yet.</div>}</section>:tab==='approved'?<section className="requestList">{approved.map(q=>{const r=requests.find(x=>x.id===q.request_id);return r?card(r,false):null})}{approved.length===0&&<div className="workflowEmpty"><strong>Approved Quotes</strong><p>No approved quotes yet.</p></div>}</section>:<section className="workflowEmpty"><strong>{title}</strong><p>No items in this section yet.</p></section>}</main>;
}
