'use client';
import {useEffect,useState} from 'react';
const U='https://vxptgfnuxboprwhgcxpd.supabase.co',K='sb_publishable_Wu0xH_TZ9L5t72BnROPtnw_9eJbG88T';
const money=n=>`$${Number(n||0).toFixed(2)}`;
export default function QuotePage(){
 const[q,setQ]=useState(null),[msg,setMsg]=useState('Loading your quote…'),[busy,setBusy]=useState(false);
 const token=typeof window!=='undefined'?window.location.pathname.split('/').filter(Boolean).pop():'';
 async function rpc(name){return fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:K,Authorization:`Bearer ${K}`,'Content-Type':'application/json'},body:JSON.stringify({p_token:token}),cache:'no-store'})}
 useEffect(()=>{if(!token)return;(async()=>{let r=await rpc('get_public_quote_v1');if(!r.ok){setMsg('This quote link is unavailable.');return}let d=await r.json();if(!d?.length){setMsg('This quote link is unavailable.');return}setQ(d[0]);setMsg('')})()},[token]);
 async function approve(){setBusy(true);let r=await rpc('approve_public_quote_v1');let d=r.ok?await r.json():false;if(d){setQ({...q,status:'approved'});setMsg('Thank you. Your quote has been approved and Ultimate Wrenchworks has been notified.')}else setMsg(q?.status==='approved'?'This quote is already approved.':'We could not approve this quote. Please contact Ultimate Wrenchworks.');setBusy(false)}
 const s={main:{maxWidth:680,margin:'0 auto',padding:'32px 18px 60px',fontFamily:'system-ui,-apple-system,sans-serif',color:'#17202a'},card:{background:'#fff',border:'1px solid #dfe5ea',borderRadius:16,padding:22,boxShadow:'0 8px 28px rgba(0,0,0,.06)'},row:{display:'flex',justifyContent:'space-between',gap:20,padding:'10px 0',borderBottom:'1px solid #edf0f2'},btn:{width:'100%',padding:'15px 18px',marginTop:20,border:0,borderRadius:10,fontSize:17,fontWeight:700,background:'#17202a',color:'#fff'}};
 if(!q)return <main style={s.main}><p style={{fontWeight:800,letterSpacing:1}}>ULTIMATE WRENCHWORKS · V1.16</p><div style={s.card}><p>{msg}</p></div></main>;
 return <main style={s.main}><p style={{fontWeight:800,letterSpacing:1}}>ULTIMATE WRENCHWORKS · V1.16</p><h1>Service Quote</h1><div style={s.card}><h2>{q.customer_name}</h2><p>{q.service_type} · {q.year_make_model}</p>{q.service_needed&&<p><b>Service:</b> {q.service_needed}</p>}<div style={s.row}><span>Labor</span><b>{money(q.labor)}</b></div><div style={s.row}><span>Parts</span><b>{money(q.parts)}</b></div><div style={s.row}><span>Service call</span><b>{money(q.service_call)}</b></div><div style={s.row}><span>Supplies</span><b>{money(q.supplies)}</b></div><div style={s.row}><span>Sales tax</span><b>{money(q.tax)}</b></div><div style={{...s.row,fontSize:20,borderBottom:0}}><strong>Total</strong><strong>{money(q.total)}</strong></div>{q.notes&&<div style={{marginTop:18,paddingTop:15,borderTop:'1px solid #edf0f2'}}><b>Quote notes</b><p>{q.notes}</p></div>}{q.status==='approved'?<p style={{fontWeight:700,marginTop:20}}>✓ Quote approved</p>:<button style={s.btn} disabled={busy} onClick={approve}>{busy?'Approving…':'Approve Quote'}</button>}{msg&&<p style={{marginTop:16,fontWeight:600}}>{msg}</p>}<p style={{fontSize:13,marginTop:20,color:'#59636e'}}>Approving this quote authorizes Ultimate Wrenchworks to schedule the quoted work. Any additional work or parts outside this quote will require further authorization.</p></div></main>;
}