'use client';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
const U='https://vxptgfnuxboprwhgcxpd.supabase.co',K='sb_publishable_Wu0xH_TZ9L5t72BnROPtnw_9eJbG88T';
const money=n=>`$${Number(n||0).toFixed(2)}`;
export default function QuotePage(){
 const {token}=useParams(),[q,setQ]=useState(null),[msg,setMsg]=useState('Loading quote…'),[busy,setBusy]=useState(false);
 async function rpc(name){return fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:K,Authorization:`Bearer ${K}`,'Content-Type':'application/json'},body:JSON.stringify({p_token:token}),cache:'no-store'})}
 useEffect(()=>{(async()=>{let r=await rpc('get_public_quote_v1');if(!r.ok){setMsg('This quote is unavailable.');return}let d=await r.json();if(!d?.length){setMsg('This quote is unavailable.');return}setQ(d[0]);setMsg('')})()},[token]);
 async function approve(){setBusy(true);let r=await rpc('approve_public_quote_v1'),d=await r.json().catch(()=>false);if(r.ok&&d===true){setQ({...q,status:'approved'});setMsg('Thank you. Your quote has been approved. Ultimate Wrenchworks will contact you to confirm scheduling.')}else setMsg('We could not approve this quote. It may already have been updated.');setBusy(false)}
 if(!q)return <main className="ownerPage"><section className="ownerLogin"><p className="kicker">ULTIMATE WRENCHWORKS · V1.16</p><h1>Service Quote</h1><p>{msg}</p></section></main>;
 return <main className="ownerPage"><section className="ownerLogin" style={{maxWidth:650}}><p className="kicker">ULTIMATE WRENCHWORKS · V1.16</p><h1>Service Quote</h1><p><b>{q.customer_name}</b></p><p>{q.service_type} · {q.year_make_model}</p>{q.service_needed&&<p><b>Service:</b> {q.service_needed}</p>}<div className="quoteSummary" style={{marginTop:20}}><p>Labor <strong>{money(q.labor)}</strong></p><p>Parts <strong>{money(q.parts)}</strong></p><p>Service call <strong>{money(q.service_call)}</strong></p><p>Supplies <strong>{money(q.supplies)}</strong></p><p>Sales tax <strong>{money(q.tax)}</strong></p><hr/><p style={{fontSize:22}}><b>Total</b> <strong>{money(q.total)}</strong></p></div>{q.notes&&<div className="requestProblem"><b>Quote notes</b><p>{q.notes}</p></div>}{q.status==='approved'?<p className="ownerMessage">{msg||'This quote has been approved. Ultimate Wrenchworks will contact you to confirm scheduling.'}</p>:<><p>By approving, you authorize Ultimate Wrenchworks to proceed with scheduling based on this quote. Additional work or parts outside this quote will require further approval.</p><button className="primary" onClick={approve} disabled={busy}>{busy?'Approving…':'Approve Quote'}</button>{msg&&<p className="ownerMessage">{msg}</p>}</>}<p style={{marginTop:24}}><a href="/">← Ultimate Wrenchworks</a></p></section></main>;
}
