'use client';

import { useEffect, useState } from 'react';

const years = Array.from({ length: 48 }, (_, i) => String(2027 - i));
const serviceOptions={
  'ATV':['Routine Maintenance / Service','Oil & Filter Change','Diagnostic / Repair','No Start / Hard Start','Battery / Electrical','Brakes','Drive Belt / CVT','Drivetrain / Axles','Cooling / Overheating','Fuel System','Suspension / Steering','Tires / Wheels','Accessory Installation'],
  'SXS / UTV':['Routine Maintenance / Service','Oil & Filter Change','Diagnostic / Repair','No Start / Hard Start','Battery / Electrical','Brakes','Drive Belt / CVT','Drivetrain / Axles','Cooling / Overheating','Fuel System','Suspension / Steering','Tires / Wheels','Accessory Installation'],
  'Motorcycle / Dirt Bike':['Routine Maintenance / Service','Oil & Filter Change','Diagnostic / Repair','No Start / Hard Start','Battery / Electrical','Brakes','Chain / Sprockets','Clutch / Transmission','Cooling / Overheating','Fuel System','Suspension / Steering','Tires / Wheels','Accessory Installation'],
  'Auto / Light Truck':['Routine Maintenance / Service','Oil & Filter Change','Diagnostic / Repair','No Start / Hard Start','Battery / Electrical','Brakes','Engine / Drivability','Cooling / Overheating','Fuel System','Steering / Suspension','Drivetrain / Axles','Tires / Wheels','Accessory Installation'],
  'Small Engine':['Routine Maintenance / Service','Oil & Filter Change','Diagnostic / Repair','No Start / Hard Start','Fuel System / Carburetor','Ignition / Electrical','Engine Repair','Belt / Drive System','Blade / Cutting System','Generator Service','Accessory / Equipment Repair'],
  'Other':['Diagnostic / Repair','Routine Maintenance / Service','Accessory Installation']
};

export default function ServiceRequestForm() {
  const [status,setStatus]=useState(''); const [submitting,setSubmitting]=useState(false); const [success,setSuccess]=useState(false);
  const [serviceType,setServiceType]=useState(''); const [serviceNeeded,setServiceNeeded]=useState(''); const [otherService,setOtherService]=useState('');
  const [year,setYear]=useState(''); const [otherYear,setOtherYear]=useState(''); const [make,setMake]=useState(''); const [otherMake,setOtherMake]=useState(''); const [model,setModel]=useState(''); const [otherModel,setOtherModel]=useState(''); const [otherVehicle,setOtherVehicle]=useState('');
  const [makes,setMakes]=useState([]); const [models,setModels]=useState([]); const [loadingMakes,setLoadingMakes]=useState(false); const [loadingModels,setLoadingModels]=useState(false);
  const [location,setLocation]=useState(''); const [travel,setTravel]=useState(null); const [travelStatus,setTravelStatus]=useState(''); const [checkingTravel,setCheckingTravel]=useState(false);
  const selectedYear=year==='Other / Not Listed'?otherYear.trim():year; const selectedMake=make==='Other / Not Listed'?otherMake.trim():make; const selectedModel=model==='Other / Not Listed'?otherModel.trim():model;
  const vehicle=serviceType==='Other'?otherVehicle.trim():[selectedYear,selectedMake,selectedModel].filter(Boolean).join(' '); const requestedService=serviceNeeded==='Other / Not Listed'?otherService.trim():serviceNeeded;

  useEffect(()=>{if(!serviceType||serviceType==='Other'||!year||year==='Other / Not Listed'){setMakes([]);setMake('');setModels([]);setModel('');return;}let cancelled=false;setLoadingMakes(true);setMake('');setModels([]);setModel('');fetch(`/api/vehicle-options?type=${encodeURIComponent(serviceType)}&year=${encodeURIComponent(year)}`).then(r=>r.json()).then(data=>{if(!cancelled)setMakes(data.makes||[]);}).catch(()=>{if(!cancelled)setMakes([]);}).finally(()=>{if(!cancelled)setLoadingMakes(false);});return()=>{cancelled=true;};},[serviceType,year]);
  useEffect(()=>{if(!serviceType||!year||year==='Other / Not Listed'||!make||make==='Other / Not Listed'){setModels([]);setModel('');return;}let cancelled=false;setLoadingModels(true);setModel('');fetch(`/api/vehicle-options?type=${encodeURIComponent(serviceType)}&year=${encodeURIComponent(year)}&make=${encodeURIComponent(make)}`).then(r=>r.json()).then(data=>{if(!cancelled)setModels(data.models||[]);}).catch(()=>{if(!cancelled)setModels([]);}).finally(()=>{if(!cancelled)setLoadingModels(false);});return()=>{cancelled=true;};},[serviceType,year,make]);
  useEffect(()=>{setTravel(null);setTravelStatus('');if(location.trim().length<8)return;const timer=setTimeout(()=>checkTravel(location),700);return()=>clearTimeout(timer);},[location]);
  function changeServiceType(value){setServiceType(value);setServiceNeeded('');setOtherService('');setYear('');setOtherYear('');setMake('');setOtherMake('');setModel('');setOtherModel('');setOtherVehicle('');setMakes([]);setModels([]);} function resetVehicle(){changeServiceType('');}
  async function checkTravel(address){setCheckingTravel(true);setTravelStatus('Calculating driving distance…');try{const response=await fetch(`/api/travel-fee?address=${encodeURIComponent(address)}`,{cache:'no-store'});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Unable to calculate distance.');setTravel(data);setTravelStatus('');}catch(error){setTravel(null);setTravelStatus(error.message||'Unable to calculate distance.');}finally{setCheckingTravel(false);}}
  async function handleSubmit(event){event.preventDefault();if(submitting)return;const formElement=event.currentTarget;const form=new FormData(formElement);const payload=Object.fromEntries(form.entries());payload.vehicle=vehicle;payload.serviceNeeded=requestedService;payload.travelDistanceMiles=travel?.miles??null;payload.travelFee=travel?.travelFee??0;const required=['name','phone','serviceType','serviceNeeded','vehicle','timeframe','location','issue'];if(required.some(key=>!String(payload[key]||'').trim())){setSuccess(false);setStatus('Please complete all required fields before submitting.');return;}if(!travel){setSuccess(false);setStatus('Please enter a complete service address so we can calculate travel distance and any travel fee.');return;}setSubmitting(true);setSuccess(false);setStatus('Submitting your service request…');try{const response=await fetch('/api/service-request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Unable to submit request.');formElement.reset();resetVehicle();setLocation('');setTravel(null);setSuccess(true);setStatus('Request received. We’ll review the details and contact you to confirm scheduling.');}catch(error){setSuccess(false);setStatus(error.message||'We could not save your request. Please try again.');}finally{setSubmitting(false);}}

  return <form className="requestForm" onSubmit={handleSubmit} noValidate><div className="formGrid">
    <label><span>Name *</span><input name="name" autoComplete="name" required /></label><label><span>Phone *</span><input name="phone" type="tel" autoComplete="tel" required /></label><label><span>Email</span><input name="email" type="email" autoComplete="email" /></label>
    <label><span>Equipment category *</span><select name="serviceType" value={serviceType} onChange={e=>changeServiceType(e.target.value)} required><option value="" disabled>Select one</option><option>ATV</option><option>SXS / UTV</option><option>Motorcycle / Dirt Bike</option><option>Auto / Light Truck</option><option>Small Engine</option><option>Other</option></select></label>
    {serviceType&&<><label className="wide"><span>Service needed *</span><select value={serviceNeeded} onChange={e=>{setServiceNeeded(e.target.value);setOtherService('');}} required><option value="" disabled>Select service</option>{(serviceOptions[serviceType]||[]).map(s=><option key={s}>{s}</option>)}<option>Other / Not Listed</option></select></label>{serviceNeeded==='Other / Not Listed'&&<label className="wide"><span>Service needed (not listed) *</span><input value={otherService} onChange={e=>setOtherService(e.target.value)} placeholder="Tell us what service you need" required /></label>}</>}
    {serviceType&&serviceType!=='Other'&&<><label><span>Year *</span><select value={year} onChange={e=>{setYear(e.target.value);setOtherYear('');setOtherMake('');setOtherModel('');}} required><option value="" disabled>Select year</option>{years.map(y=><option key={y}>{y}</option>)}<option>Other / Not Listed</option></select></label>{year==='Other / Not Listed'?<><label><span>Year (not listed) *</span><input value={otherYear} onChange={e=>setOtherYear(e.target.value)} placeholder="Example: 1978" inputMode="numeric" required /></label><label><span>Make *</span><input value={otherMake} onChange={e=>setOtherMake(e.target.value)} placeholder="Enter manufacturer" required /></label><label className="wide"><span>Model *</span><input value={otherModel} onChange={e=>setOtherModel(e.target.value)} placeholder="Enter model" required /></label></>:year&&<><label><span>Make *</span><select value={make} onChange={e=>{setMake(e.target.value);setOtherMake('');setOtherModel('');}} required disabled={loadingMakes}><option value="" disabled>{loadingMakes?'Loading makes…':'Select make'}</option>{makes.map(m=><option key={m}>{m}</option>)}<option>Other / Not Listed</option></select></label>{make==='Other / Not Listed'&&<label><span>Make (not listed) *</span><input value={otherMake} onChange={e=>setOtherMake(e.target.value)} placeholder="Enter manufacturer" required /></label>}{make&&make!=='Other / Not Listed'&&<label className="wide"><span>Model *</span><select value={model} onChange={e=>setModel(e.target.value)} required disabled={loadingModels}><option value="" disabled>{loadingModels?'Loading models…':'Select model'}</option>{models.map(m=><option key={m}>{m}</option>)}<option>Other / Not Listed</option></select></label>}{make==='Other / Not Listed'&&<label className="wide"><span>Model *</span><input value={otherModel} onChange={e=>setOtherModel(e.target.value)} placeholder="Enter model" required /></label>}{model==='Other / Not Listed'&&<label className="wide"><span>Model (not listed) *</span><input value={otherModel} onChange={e=>setOtherModel(e.target.value)} placeholder="Enter model" required /></label>}</>}</>}
    {serviceType==='Other'&&<label className="wide"><span>Year / Make / Model *</span><input value={otherVehicle} onChange={e=>setOtherVehicle(e.target.value)} placeholder="Enter equipment year, make and model" required /></label>}<input type="hidden" name="vehicle" value={vehicle} /><input type="hidden" name="serviceNeeded" value={requestedService} />
    <label><span>Preferred date</span><input name="date" type="date" /></label><label><span>Preferred timeframe *</span><select name="timeframe" defaultValue="" required><option value="" disabled>Select a timeframe</option><option value="Morning 9-12">Morning 9–12</option><option value="Afternoon 12-4">Afternoon 12–4</option><option value="Evening 6-8">Evening 6–8</option></select></label>
    <label className="wide"><span>Service location *</span><input name="location" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Full street address, city, state and ZIP" autoComplete="street-address" required /></label>
    <div className="wide travelEstimate" aria-live="polite"><b>Mobile service travel</b>{checkingTravel&&<p>Calculating driving distance…</p>}{!checkingTravel&&travel&&<><strong>{travel.miles.toFixed(1)} miles away</strong><p>{travel.miles<=travel.freeMiles?`Within the first ${travel.freeMiles} miles — no additional mileage charge.`:`Travel fee: $${travel.travelFee.toFixed(2)} · $${travel.ratePerMile.toFixed(2)} per mile beyond ${travel.freeMiles} miles.`}</p></>}{!checkingTravel&&!travel&&<p>{travelStatus||'The first 25 miles are included. Travel beyond 25 miles is charged at $1.00 per mile.'}</p>}</div>
    <label className="wide"><span>What is it doing / additional details? *</span><textarea name="issue" rows="5" minLength="10" placeholder="Describe symptoms, warning lights, noises, leaks, or anything else that will help us prepare." required /></label>
  </div><label className="hpField" aria-hidden="true">Company<input name="company" tabIndex="-1" autoComplete="off" /></label><div className="formFooter"><button className="primary light" type="submit" disabled={submitting}>{submitting?'Submitting…':'Submit Service Request'}</button><p>A $100 diagnostic fee may apply to diagnostic service. The first 25 travel miles are included; travel beyond 25 miles is $1.00 per mile. Appointment is confirmed only after we contact you.</p></div>{status&&<p className={`formStatus ${success?'success':''}`} role="status">{status}</p>}</form>;
}
