'use client';

import { useEffect, useState } from 'react';
import VinCameraScanner from './VinCameraScanner';

const years = Array.from({ length: 48 }, (_, i) => String(2027 - i));
const serviceOptions={
  'ATV':['Routine Maintenance / Service','Oil & Filter Change','Diagnostic / Repair','No Start / Hard Start','Battery / Electrical','Brakes','Drive Belt / CVT','Drivetrain / Axles','Cooling / Overheating','Fuel System','Suspension / Steering','Tires / Wheels','Accessory Installation'],
  'SXS / UTV':['Routine Maintenance / Service','Oil & Filter Change','Diagnostic / Repair','No Start / Hard Start','Battery / Electrical','Brakes','Drive Belt / CVT','Drivetrain / Axles','Cooling / Overheating','Fuel System','Suspension / Steering','Tires / Wheels','Accessory Installation'],
  'Motorcycle / Dirt Bike':['Routine Maintenance / Service','Oil & Filter Change','Diagnostic / Repair','No Start / Hard Start','Battery / Electrical','Brakes','Chain / Sprockets','Clutch / Transmission','Cooling / Overheating','Fuel System','Suspension / Steering','Tires / Wheels','Accessory Installation'],
  'Auto / Light Truck':['Routine Maintenance / Service','Oil & Filter Change','Diagnostic / Repair','No Start / Hard Start','Battery / Electrical','Brakes','Engine / Drivability','Cooling / Overheating','Fuel System','Steering / Suspension','Drivetrain / Axles','Tires / Wheels','Accessory Installation'],
  'Small Engine':['Routine Maintenance / Service','Oil & Filter Change','Diagnostic / Repair','No Start / Hard Start','Fuel System / Carburetor','Ignition / Electrical','Engine Repair','Belt / Drive System','Blade / Cutting System','Generator Service','Accessory / Equipment Repair'],
  'Experienced Mechanic Helper':['Hands-On Repair Assistance — $75/hr','Troubleshooting Assistance — $50/hr','Assembly / Installation Assistance — $75/hr','Heavy Component Help / Second Set of Hands — $100/hr'],
  'Other':['Diagnostic / Repair','Routine Maintenance / Service','Accessory Installation']
};

const stateOptions=['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY','DC'];

const autoServiceDetails={
  'Routine Maintenance':['Oil & Filter Change','Factory / Mileage-Based Maintenance','Fluid Service','Tune-Up / Preventive Maintenance','Pre-Purchase / General Inspection'],
  'Diagnostics & Electrical':['Check Engine Light / Warning Light','No Start / Hard Start','Battery / Starting / Charging','Electrical Diagnosis','General Diagnostic / Drivability'],
  'Brakes / Tires / Suspension':['Brake Service / Repair','Tire / Wheel Service','Steering / Suspension Repair','Wheel Bearing / Hub','Alignment-Related Inspection'],
  'Engine / Cooling / Fuel':['Engine Performance / Misfire','Cooling System / Overheating','Fuel System Repair','Leak Diagnosis / Repair','Engine Repair'],
  'Drivetrain':['Transmission / Drivetrain Diagnosis','Axle / CV Joint','Differential / Transfer Case','Clutch / Manual Transmission','Driveshaft / U-Joint'],
  'Accessories & Other':['Accessory Installation','Trailer / Towing Electrical','Lighting Upgrade / Repair','Other Repair / Service']
};

export default function ServiceRequestForm() {
  const [status,setStatus]=useState(''); const [submitting,setSubmitting]=useState(false); const [success,setSuccess]=useState(false);
  const [serviceType,setServiceType]=useState(''); const [serviceNeeded,setServiceNeeded]=useState(''); const [serviceDetail,setServiceDetail]=useState(''); const [otherService,setOtherService]=useState('');
  const [year,setYear]=useState(''); const [otherYear,setOtherYear]=useState(''); const [make,setMake]=useState(''); const [otherMake,setOtherMake]=useState(''); const [model,setModel]=useState(''); const [otherModel,setOtherModel]=useState(''); const [otherVehicle,setOtherVehicle]=useState(''); const [engineSize,setEngineSize]=useState('');
  const [vin,setVin]=useState(''); const [vinData,setVinData]=useState(null); const [vinStatus,setVinStatus]=useState(''); const [decodingVin,setDecodingVin]=useState(false); const [vinConfirmed,setVinConfirmed]=useState(false); const [showVinHelp,setShowVinHelp]=useState(false);
  const [makes,setMakes]=useState([]); const [models,setModels]=useState([]); const [loadingMakes,setLoadingMakes]=useState(false); const [loadingModels,setLoadingModels]=useState(false);
  const [street,setStreet]=useState(''); const [city,setCity]=useState(''); const [serviceState,setServiceState]=useState(''); const [zip,setZip]=useState(''); const [travel,setTravel]=useState(null); const [travelStatus,setTravelStatus]=useState(''); const [checkingTravel,setCheckingTravel]=useState(false);

  const selectedYear=year==='Other / Not Listed'?otherYear.trim():year;
  const selectedMake=make==='Other / Not Listed'?otherMake.trim():make;
  const selectedModel=model==='Other / Not Listed'?otherModel.trim():model;
  const manualVehicle=[selectedYear,selectedMake,selectedModel].filter(Boolean).join(' ');
  const decodedVehicle=vinData?[vinData.year,vinData.make,vinData.model,vinData.trim||vinData.series].filter(Boolean).join(' '):'';
  const isPowersports=['ATV','SXS / UTV','Motorcycle / Dirt Bike'].includes(serviceType);
  const isMechanicHelper=serviceType==='Experienced Mechanic Helper';
  const supportsVinLookup=isPowersports||serviceType==='Auto / Light Truck'||isMechanicHelper;
  const baseVehicle=serviceType==='Other'?otherVehicle.trim():(supportsVinLookup&&vinData?.complete?decodedVehicle:(isMechanicHelper?otherVehicle.trim():manualVehicle));
  const resolvedEngine=vinData?.engineDescription||engineSize.trim();
  const vehicle=supportsVinLookup&&resolvedEngine&&baseVehicle?`${baseVehicle} · Engine ${resolvedEngine}`:baseVehicle;
  const requestedService=serviceType==='Auto / Light Truck'?(serviceDetail==='Other / Not Listed'?otherService.trim():(serviceNeeded&&serviceDetail?`${serviceNeeded} — ${serviceDetail}`:serviceDetail)):serviceNeeded==='Other / Not Listed'?otherService.trim():serviceNeeded;

  const location=[street.trim(),city.trim(),serviceState,zip.trim()].filter(Boolean).join(', ').replace(/, ([A-Z]{2}), (\d{5}(?:-\d{4})?)$/, ', $1 $2');

  useEffect(()=>{if(!serviceType||serviceType==='Other'||serviceType==='Auto / Light Truck'||!year||year==='Other / Not Listed'){setMakes([]);setMake('');setModels([]);setModel('');return;}let cancelled=false;setLoadingMakes(true);setMake('');setModels([]);setModel('');fetch(`/api/vehicle-options?type=${encodeURIComponent(serviceType)}&year=${encodeURIComponent(year)}`).then(r=>r.json()).then(data=>{if(!cancelled)setMakes(data.makes||[]);}).catch(()=>{if(!cancelled)setMakes([]);}).finally(()=>{if(!cancelled)setLoadingMakes(false);});return()=>{cancelled=true;};},[serviceType,year]);
  useEffect(()=>{if(!serviceType||serviceType==='Auto / Light Truck'||!year||year==='Other / Not Listed'||!make||make==='Other / Not Listed'){setModels([]);setModel('');return;}let cancelled=false;setLoadingModels(true);setModel('');fetch(`/api/vehicle-options?type=${encodeURIComponent(serviceType)}&year=${encodeURIComponent(year)}&make=${encodeURIComponent(make)}`).then(r=>r.json()).then(data=>{if(!cancelled)setModels(data.models||[]);}).catch(()=>{if(!cancelled)setModels([]);}).finally(()=>{if(!cancelled)setLoadingModels(false);});return()=>{cancelled=true;};},[serviceType,year,make]);
  useEffect(()=>{function selectCategory(event){const value=event?.detail?.serviceType;if(value)changeServiceType(value);}window.addEventListener('uw:select-service-type',selectCategory);return()=>window.removeEventListener('uw:select-service-type',selectCategory);},[]);
  useEffect(()=>{if(!supportsVinLookup||vin.length!==17){setVinConfirmed(false);return;}const timer=setTimeout(()=>decodeVin(vin),250);return()=>clearTimeout(timer);},[vin,serviceType]);

  function changeServiceType(value){setServiceType(value);setServiceNeeded('');setServiceDetail('');setOtherService('');setYear('');setOtherYear('');setMake('');setOtherMake('');setModel('');setOtherModel('');setOtherVehicle('');setEngineSize('');setVin('');setVinData(null);setVinStatus('');setVinConfirmed(false);setShowVinHelp(false);setMakes([]);setModels([]);}
  function resetVehicle(){changeServiceType('');}

  async function decodeVin(value=vin){
    const clean=String(value||'').toUpperCase().replace(/[^A-HJ-NPR-Z0-9]/g,'');
    setVin(clean); setVinData(null); setVinConfirmed(false);
    if(clean.length!==17){setVinStatus('Enter the complete 17-character VIN.');return;}
    setDecodingVin(true); setVinStatus('Decoding VIN…');
    try{
      const response=await fetch(`/api/vin-decode?vin=${encodeURIComponent(clean)}&type=${encodeURIComponent(serviceType)}`,{cache:'no-store'});
      const data=await response.json();
      if(!response.ok||!data.ok)throw new Error(data.error||'Unable to decode VIN.');
      setVinData(data); setVinStatus(data.complete?'Vehicle identified from VIN data.':'VIN recognized, but complete model details were not available. Please confirm year, make and model below.');
      setEngineSize(data.engineSize||'');
    }catch(error){setVinData(null);setVinStatus(error.message||'VIN could not be decoded. Please verify the VIN and try again.');}
    finally{setDecodingVin(false);}
  }

  function hasCompleteServiceAddress(address){
    const clean=String(address||'').trim();
    const hasZip=/\b\d{5}(?:-\d{4})?\b/.test(clean);
    const hasState=/\b(?:AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC)\b/i.test(clean);
    return clean.length>=12&&hasZip&&hasState;
  }

  async function checkTravel(address){const clean=String(address||'').trim();if(!hasCompleteServiceAddress(clean)){setTravel(null);setTravelStatus('Enter the full street address, city, state, and ZIP before calculating distance.');return null;}setCheckingTravel(true);setTravelStatus('Calculating driving distance…');try{const params=new URLSearchParams({street:street.trim(),city:city.trim(),state:serviceState,zip:zip.trim()});const response=await fetch(`/api/travel-fee?${params.toString()}`,{cache:'no-store'});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Unable to calculate distance.');setTravel(data);setTravelStatus('');return data;}catch(error){setTravel(null);setTravelStatus(error.message||'Unable to calculate distance.');return null;}finally{setCheckingTravel(false);}}

  async function handleSubmit(event){
    event.preventDefault();
    if(submitting)return;
    const formElement=event.currentTarget;
    const form=new FormData(formElement);
    const payload=Object.fromEntries(form.entries());
    payload.serviceType=serviceType;
    payload.vehicle=vehicle;
    payload.serviceNeeded=requestedService;
    payload.vin=(serviceType==='Auto / Light Truck'||isPowersports||isMechanicHelper)?vin:'';
    payload.engineSize=resolvedEngine;
    payload.location=location;
    if(serviceType==='Auto / Light Truck'&&!vinData?.complete){setSuccess(false);setStatus('Please enter a valid 17-character VIN and wait for the vehicle lookup to complete before submitting.');return;}
    if(vinData?.complete&&!vinConfirmed){setSuccess(false);setStatus('Please confirm that the vehicle identified from the VIN is correct.');return;}
    const requiredRules={name:{label:'Name',min:2},phone:{label:'Phone',min:7},serviceType:{label:'Equipment category',min:1},serviceNeeded:{label:'Service needed',min:2},vehicle:{label:'Vehicle',min:2},location:{label:'Service location',min:5},issue:{label:'Additional details',min:10}};
    const missing=Object.keys(requiredRules).filter(key=>String(payload[key]||'').trim().length<requiredRules[key].min);
    if(missing.length){const first=missing[0];setSuccess(false);setStatus(`Please complete: ${missing.map(key=>requiredRules[key].label).join(', ')}${missing.includes('issue')?' (additional details must be at least 10 characters)':''}.`);const field=formElement.elements.namedItem(first);if(field&&typeof field.focus==='function'){field.focus();field.scrollIntoView?.({behavior:'smooth',block:'center'});}return;}
    let currentTravel=travel;
    if(!currentTravel){currentTravel=await checkTravel(payload.location);if(!currentTravel){setSuccess(false);setStatus('Please verify the service address so we can calculate driving distance.');return;}}
    payload.travelDistanceMiles=currentTravel.miles; payload.travelFee=currentTravel.travelFee??0;
    setSubmitting(true);setSuccess(false);setStatus('Submitting your quote request…');
    try{const response=await fetch('/api/service-request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Unable to submit request.');formElement.reset();resetVehicle();setStreet('');setCity('');setServiceState('');setZip('');setTravel(null);setSuccess(true);setStatus('Quote request received. We’ll review the details and send your quote before any scheduling takes place.');}
    catch(error){setSuccess(false);setStatus(error.message||'We could not save your request. Please try again.');}
    finally{setSubmitting(false);}
  }

  return <form className="requestForm" onSubmit={handleSubmit} noValidate><div className="formGrid">
    <label><span>Name *</span><input name="name" autoComplete="name" required /></label><label><span>Phone *</span><input name="phone" type="tel" autoComplete="tel" required /></label><label><span>Email</span><input name="email" type="email" autoComplete="email" /></label>
    <label><span>Equipment category *</span><select name="serviceType" value={serviceType} onChange={e=>changeServiceType(e.target.value)} required><option value="" disabled>Select one</option><option>ATV</option><option>SXS / UTV</option><option>Motorcycle / Dirt Bike</option><option>Auto / Light Truck</option><option>Small Engine</option><option>Experienced Mechanic Helper</option><option>Other</option></select></label>
    {serviceType&&serviceType!=='Auto / Light Truck'&&<><label className="wide"><span>Service needed *</span><select value={serviceNeeded} onChange={e=>{setServiceNeeded(e.target.value);setOtherService('');}} required><option value="" disabled>Select service</option>{(serviceOptions[serviceType]||[]).map(s=><option key={s}>{s}</option>)}<option>Other / Not Listed</option></select></label>{serviceNeeded==='Other / Not Listed'&&<label className="wide"><span>Service needed (not listed) *</span><input value={otherService} onChange={e=>setOtherService(e.target.value)} placeholder="Tell us what service you need" required /></label>}</>}
    {serviceType==='Auto / Light Truck'&&<><label className="wide"><span>Service category *</span><select value={serviceNeeded} onChange={e=>{setServiceNeeded(e.target.value);setServiceDetail('');setOtherService('');}} required><option value="" disabled>Select category</option>{Object.keys(autoServiceDetails).map(s=><option key={s}>{s}</option>)}</select></label>{serviceNeeded&&<label className="wide"><span>Specific service *</span><select value={serviceDetail} onChange={e=>{setServiceDetail(e.target.value);setOtherService('');}} required><option value="" disabled>Select specific service</option>{(autoServiceDetails[serviceNeeded]||[]).map(s=><option key={s}>{s}</option>)}<option>Other / Not Listed</option></select></label>}{serviceDetail==='Other / Not Listed'&&<label className="wide"><span>Specific service (not listed) *</span><input value={otherService} onChange={e=>setOtherService(e.target.value)} placeholder="Tell us what service you need" required /></label>}</>}
    {supportsVinLookup&&<div className="wide travelEstimate" aria-live="polite"><b>{serviceType} VIN</b><p>{serviceType==='Auto / Light Truck'?'Enter or scan the 17-character VIN. The vehicle will be identified automatically.':isMechanicHelper?'Enter or scan the 17-character VIN for automatic vehicle lookup. If the VIN does not return complete details, enter the vehicle information manually below.':'Enter or scan the 17-character VIN. We’ll automatically look up any available vehicle details.'}</p><label><span>VIN {serviceType==='Auto / Light Truck'?'*':'(recommended)'}</span><input name="vin" value={vin} onChange={e=>{setVin(e.target.value.toUpperCase().replace(/[^A-HJ-NPR-Z0-9]/g,''));setVinData(null);setVinStatus('');setVinConfirmed(false);}} maxLength="17" autoCapitalize="characters" autoCorrect="off" spellCheck="false" placeholder="17-character VIN" required={serviceType==='Auto / Light Truck'} /></label><VinCameraScanner onVin={value=>{setVin(value);setVinData(null);setVinConfirmed(false);setVinStatus('VIN captured. Looking up vehicle…');}} /><button className="secondary" type="button" onClick={()=>setShowVinHelp(true)} style={{marginTop:'10px'}}>Where do I find my VIN?</button>{decodingVin&&<p>Looking up vehicle…</p>}{!decodingVin&&vinStatus&&<p>{vinStatus}</p>}{vinData&&<><strong>{[vinData.year,vinData.make,vinData.model,vinData.trim||vinData.series].filter(Boolean).join(' ')}</strong><p>{vinData.vehicleType?`Vehicle type: ${vinData.vehicleType}. `:''}{vinData.engineDescription||(!vinData.complete?'Complete model details were not returned; confirm the missing details below.':'')}</p>{vinData.complete&&<label style={{display:'flex',gap:'10px',alignItems:'flex-start',marginTop:'12px'}}><input type="checkbox" checked={vinConfirmed} onChange={e=>setVinConfirmed(e.target.checked)} style={{width:'20px',height:'20px',marginTop:'2px',flex:'0 0 auto'}}/><span><strong>I confirm this is the correct vehicle.</strong></span></label>}</>}</div>}
    {showVinHelp&&<div role="dialog" aria-modal="true" aria-labelledby="vin-help-title" onClick={()=>setShowVinHelp(false)} style={{position:'fixed',inset:0,background:'rgba(0,0,0,.6)',display:'flex',alignItems:'center',justifyContent:'center',padding:'20px',zIndex:1000}}><div onClick={e=>e.stopPropagation()} style={{background:'#fff',color:'#111',width:'min(92vw,520px)',borderRadius:'14px',padding:'22px',boxShadow:'0 12px 40px rgba(0,0,0,.28)'}}><h3 id="vin-help-title" style={{marginTop:0}}>Where do I find my VIN?</h3><p>Your VIN is a unique 17-character number that identifies your exact vehicle.</p><p><strong>Common locations:</strong> look through the windshield at the driver-side dashboard, on the driver-side door jamb or door sticker, or on your vehicle registration or insurance card.</p><p><strong>Why we need it:</strong> the VIN helps us identify the exact year, model, engine, trim and factory configuration. That lets Ultimate Wrenchworks select the correct parts for your vehicle and build a more accurate quote before service begins.</p><p>Using the VIN helps reduce incorrect parts, delays and changes to your estimate.</p><button className="primary light" type="button" onClick={()=>setShowVinHelp(false)}>Got it</button></div></div>}
    {serviceType&&serviceType!=='Other'&&serviceType!=='Auto / Light Truck'&&serviceType!=='Experienced Mechanic Helper'&&(!isPowersports||!vinData?.complete)&&<><label><span>Year *</span><select value={year} onChange={e=>{setYear(e.target.value);setOtherYear('');setOtherMake('');setOtherModel('');setEngineSize('');}} required><option value="" disabled>Select year</option>{years.map(y=><option key={y}>{y}</option>)}<option>Other / Not Listed</option></select></label>{year==='Other / Not Listed'?<><label><span>Year (not listed) *</span><input value={otherYear} onChange={e=>setOtherYear(e.target.value)} placeholder="Example: 1978" inputMode="numeric" required /></label><label><span>Make *</span><input value={otherMake} onChange={e=>setOtherMake(e.target.value)} placeholder="Enter manufacturer" required /></label><label className="wide"><span>Model *</span><input value={otherModel} onChange={e=>setOtherModel(e.target.value)} placeholder="Enter model" required /></label></>:year&&<><label><span>Make *</span><select value={make} onChange={e=>{setMake(e.target.value);setOtherMake('');setOtherModel('');setEngineSize('');}} required disabled={loadingMakes}><option value="" disabled>{loadingMakes?'Loading makes…':'Select make'}</option>{makes.map(m=><option key={m}>{m}</option>)}<option>Other / Not Listed</option></select></label>{make==='Other / Not Listed'&&<label><span>Make (not listed) *</span><input value={otherMake} onChange={e=>setOtherMake(e.target.value)} placeholder="Enter manufacturer" required /></label>}{make&&make!=='Other / Not Listed'&&<label className="wide"><span>Model *</span><select value={model} onChange={e=>{setModel(e.target.value);setEngineSize('');}} required disabled={loadingModels}><option value="" disabled>{loadingModels?'Loading models…':'Select model'}</option>{models.map(m=><option key={m}>{m}</option>)}<option>Other / Not Listed</option></select></label>}{make==='Other / Not Listed'&&<label className="wide"><span>Model *</span><input value={otherModel} onChange={e=>setOtherModel(e.target.value)} placeholder="Enter model" required /></label>}{model==='Other / Not Listed'&&<label className="wide"><span>Model (not listed) *</span><input value={otherModel} onChange={e=>setOtherModel(e.target.value)} placeholder="Enter model" required /></label>}</>}</>}
    {serviceType==='Other'&&<label className="wide"><span>Year / Make / Model *</span><input value={otherVehicle} onChange={e=>setOtherVehicle(e.target.value)} placeholder="Enter equipment year, make and model" required /></label>}{isMechanicHelper&&!vinData?.complete&&<label className="wide"><span>Year / Make / Model *</span><input value={otherVehicle} onChange={e=>setOtherVehicle(e.target.value)} placeholder="Enter vehicle year, make and model if VIN lookup is unavailable" required /></label>}{serviceType==='Experienced Mechanic Helper'&&<div className="wide travelEstimate"><b>Experienced Mechanic Helper pricing</b><p><strong>Hands-On Repair Assistance:</strong> $75/hr<br/><strong>Troubleshooting Assistance:</strong> $50/hr<br/><strong>Assembly / Installation Assistance:</strong> $75/hr<br/><strong>Heavy Component Help / Second Set of Hands:</strong> $100/hr</p><p>Plus the <strong>$75 mobile service call</strong>. The first 25 travel miles are included; the existing mileage charge applies beyond 25 miles.</p><p>This service is for experienced hands-on mechanical assistance with your repair, troubleshooting, assembly, or installation project.</p></div>}<input type="hidden" name="vehicle" value={vehicle} /><input type="hidden" name="serviceNeeded" value={requestedService} />
    <div className="wide"><span style={{display:'block',fontWeight:700,marginBottom:'8px'}}>Service location *</span><div className="formGrid" style={{margin:0}}><label className="wide"><span>Street address *</span><input name="street" value={street} onChange={e=>{setStreet(e.target.value);setTravel(null);setTravelStatus('');}} placeholder="905 Waverly Ct" autoComplete="street-address" required /></label><label><span>City *</span><input name="city" value={city} onChange={e=>{setCity(e.target.value);setTravel(null);setTravelStatus('');}} placeholder="Opelika" autoComplete="address-level2" required /></label><label><span>State *</span><select name="state" value={serviceState} onChange={e=>{setServiceState(e.target.value);setTravel(null);setTravelStatus('');}} autoComplete="address-level1" required><option value="" disabled>Select state</option>{stateOptions.map(s=><option key={s} value={s}>{s}</option>)}</select></label><label><span>ZIP code *</span><input name="zip" value={zip} onChange={e=>{setZip(e.target.value.replace(/[^0-9-]/g,'').slice(0,10));setTravel(null);setTravelStatus('');}} onBlur={()=>{if(hasCompleteServiceAddress(location))checkTravel(location);}} placeholder="36801" autoComplete="postal-code" inputMode="numeric" required /></label><input type="hidden" name="location" value={location} /></div></div>
    <div className="wide travelEstimate" aria-live="polite"><b>Mobile service travel</b>{checkingTravel&&<p>Calculating driving distance…</p>}{!checkingTravel&&travel&&<><strong>{travel.miles.toFixed(1)} miles away</strong><p>{travel.miles<=travel.freeMiles?`Within the first ${travel.freeMiles} miles — no additional mileage charge.`:`Travel fee: $${travel.travelFee.toFixed(2)} · $${travel.ratePerMile.toFixed(2)} per mile beyond ${travel.freeMiles} miles.`}</p></>}{!checkingTravel&&!travel&&<p>{travelStatus||'Enter the street address, city, state, and ZIP. Distance will calculate after the full address is complete. The first 25 miles are included.'}</p>}{!checkingTravel&&<button className="secondary" type="button" onClick={()=>checkTravel(location)}>Calculate distance</button>}</div>
    <label className="wide"><span>What is it doing / additional details? *</span><textarea name="issue" rows="5" minLength="10" placeholder="Describe symptoms, warning lights, noises, leaks, or anything else that will help us prepare." required /></label>
    <div className="wide" style={{border:'2px solid #17202a',borderRadius:'10px',padding:'16px',background:'#fff'}}>
      <div style={{background:'#fff3cd',border:'2px solid #b8860b',borderRadius:'8px',padding:'12px 14px',marginBottom:'14px',color:'#17202a',fontSize:'17px',lineHeight:1.45,fontWeight:700}}>
        Prefer email only? Leave the SMS box unchecked. Your estimates, quotes, and other service communications will still be sent to your email address.
      </div>
      <label style={{display:'flex',gap:'10px',alignItems:'flex-start',fontWeight:400}}><input name="smsConsent" type="checkbox" value="yes" style={{width:'20px',height:'20px',marginTop:'3px',flex:'0 0 auto'}}/><span><strong>Optional SMS consent</strong><br/>I agree to receive transactional text messages from Ultimate Wrenchworks about my service request, estimates and quote links, scheduling, service updates, invoices, and payment notifications. Message frequency varies. Message and data rates may apply. Reply STOP to opt out or HELP for help. Consent is not a condition of purchase. See our <a href="/privacy" target="_blank" rel="noreferrer">Privacy Policy</a> and <a href="/terms" target="_blank" rel="noreferrer">Terms & Conditions</a>.</span></label>
    </div>
  </div><label className="hpField" aria-hidden="true">Company<input name="company" tabIndex="-1" autoComplete="off" /></label><div className="formFooter"><button className="primary light" type="submit" disabled={submitting}>{submitting?'Submitting…':'Request Quote'}</button><p>A $100 diagnostic fee may apply to diagnostic service. The first 25 travel miles are included; travel beyond 25 miles is $1.00 per mile. Scheduling becomes available after you approve your quote. Appointment is confirmed only after we contact you.</p></div>{status&&<p className={`formStatus ${success?'success':''}`} role="status">{status}</p>}</form>;
}
